# Typical submit file options
universe = vanilla
log    = logs/$(Cluster)_l$(l_mode)_d$(qnm_delta).log
error  = logs/$(Cluster)_l$(l_mode)_d$(qnm_delta).err
output = logs/$(Cluster)_l$(l_mode)_d$(qnm_delta).out

# Fill in with your own script, arguments and input files
executable = /cvmfs/software.igwn.org/conda/condabin/conda
arguments = run -n pinns python QNMPINN.py --mode $(l_mode) --delta $(qnm_delta)

# Resource requirements
request_cpus = 1
request_memory = 2GB
request_gpus = 1

notification = Never
notify_user = 2665592k@student.gla.ac.uk

stream_output = true

# Number of jobs (Using spaces instead of commas to ensure perfect parsing)
queue l_mode, qnm_delta from (
    2 0.1
    2 0.2
    2 0.5
    2 0.6
    2 0.7
    3 0.1
    3 0.2
    3 0.5
    3 0.6
    3 0.7
    4 0.1
    4 0.2
    4 0.5
    4 0.6
    4 0.7
    5 0.1
    5 0.2
    5 0.5
    5 0.6
    5 0.7
    6 0.1
    6 0.2
    6 0.5
    6 0.6
    6 0.7
)